### ISSUE TITLE
Incorrect default inputMode

### ISSUE THREAD

**Issue by leviFrosty** [AstrOOnauta/react-native-international-phone-number#45]
https://github.com/AstrOOnauta/react-native-international-phone-number/blob/aece824fae6b4462e6181034da669ee9e33e5afc/lib/index.js#L371C16-L371C16

This line is being overridden, somewhere. Resulting in the default `decimal` inputMode, which is undesirable.

Your snack example also shows the final rendered component using `decimal` inputMode.

Easy workaround: Pass inputMode prop to `<PhoneInput>` component.

**Comment by AstrOOnauta** [comment]
Sorry, but I dont understand your question. Please, can you reformulate it?

The question is about the input `keyboardType`? You need custom it? or only add other type of keyboardType different of the `numeric`?

**Comment by leviFrosty** [comment]
According to your code, it should render with `numeric` inputMode. When it renders, it renders with `decimal` input mode.

Actual:
![IMG_5382](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/79994715/99ed2a4d-e205-48d2-80a1-b4a886f0aad9)

Expected:
![IMG_5384](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/79994715/022f4940-a094-4089-98bd-0a241db5deff)

**Comment by AstrOOnauta** [comment]
@leviFrosty This is not a trouble, because the lib doesnt allow non-numeric values into input (if you tap any value non-numeric, the lib skip it). 
And changing the keyboardType will work only with iOS, but Android will show the dot (.) and comma (,) inside keyboard.

But I can add a custom `keyboardType` to the lib..I will do this in the next version.

🚀 AstrOOnauta 🚀
