### ISSUE TITLE
Issue: Autofill is broken due to clipping.

### ISSUE THREAD

**Issue by GMoon777** [AstrOOnauta/react-native-international-phone-number#47]
I can't confirm this is an issue on android but for iOS, when pasting a keyboard suggested phone number (as is commonly presented for autofill contact info) the input clips the end of the number and will double up on the country code, for example auto filling +44 12345 123 123 the input will show 44 12345 123 1 as the it would exceed the maximum length. 

I think it's because of how this library treats the country code and the phone number as seperate inputs, surely there must be some way to fix this as not allowing users to autofill numbers is a bad user experience.

**Comment by AstrOOnauta** [comment]
@GMoon777 sorry for this...and thanks for your PR!! and this issue is a great point!!

But, for now..your PR does not solve this issue (I have tested it).

I will study a better way to solve this
Maybe... when add the autofill, I will detect the calling code and set the country on flag container and add the appropriate mask according with the country detected.

I reply here soon...

🚀 AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
@GMoon777 Thanks for your patience and disposition

I release a new version fixing this issue. So, update your lib for the latest version `v.0.7.5`.

🚀 AstrOOnauta 🚀
