### ISSUE TITLE
Why not improving react-native-country-code-picker?

### ISSUE THREAD

**Issue by GeorgeHop** [AstrOOnauta/react-native-international-phone-number#56]
I see that this library based on my component, thanks, but for me it looks strange. 
Why not updating existing component? But create new?

**Comment by AstrOOnauta** [comment]
@GeorgeHop hey thanks for your lib...its amazing and beautiful!

So, at first I didn't use your `react-native-country-codes-picker` library...only after v5(I didn't know your lib). I started using the lib `react-native-country-picker-modal`, but this lib was not up to date (the last version was 3 years ago).
When I created the `react-native-international-phone-number` lib, I didn't find anything that came close to its functionality... and step by step I adjusted it until I arrived at your lib (excellent UI). so I've been using it ever since...

Is this..

🚀 AstrOOnauta 🚀
